FROM microsoft/cntk:2.4-gpu-python3.5-cuda9.0-cudnn7.0

LABEL maintainer "MICROSOFT CORPORATION"

RUN /root/anaconda3/envs/cntk-py35/bin/conda install -y -n cntk-py35 cython boost

RUN apt-get update && apt-get install -y python-pip 
RUN apt-get install -y  git

RUN pip install dlib easydict pyyaml
#RUN cd /cntk/Examples/Image/Detection/utils && git clone https://github.com/CatalystCode/py-faster-rcnn.git && cd py-faster-rcnn/lib && python setup.py build_ext --inplace
#RUN cp /cntk/Examples/Image/Detection/utils/py-faster-rcnn/lib/pycocotools/_mask.cpython-35m-x86_64-linux-gnu.so /cntk/Examples/Image/Detection/utils/cython_modules/ 
#RUN cp /cntk/Examples/Image/Detection/utils/py-faster-rcnn/lib/utils/cython_bbox.cpython-35m-x86_64-linux-gnu.so /cntk/Examples/Image/Detection/utils/cython_modules/ 
#RUN cp /cntk/Examples/Image/Detection/utils/py-faster-rcnn/lib/nms/gpu_nms.cpython-35m-x86_64-linux-gnu.so /cntk/Examples/Image/Detection/utils/cython_modules/ 
#RUN cp /cntk/Examples/Image/Detection/utils/py-faster-rcnn/lib/nms/cpu_nms.cpython-35m-x86_64-linux-gnu.so /cntk/Examples/Image/Detection/utils/cython_modules/ 

WORKDIR /cntk/Examples/Image/Detection/FasterRCNN
RUN git config --system core.longpaths true
RUN pip install "git+https://github.com/Azure/azure-sdk-for-python#egg=azure-cognitiveservices-vision-customvision&subdirectory=azure-cognitiveservices-vision-customvision"
COPY . /cv_workshop
WORKDIR /cv_workshop
RUN pip install opencv-python
RUN pip install -r cli-requirements.txt

#RUN python -u cvworkshop_utils.py

CMD bash -c 'jupyter-notebook --ip=0.0.0.0 --allow-root --no-browser'
